/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
static yyconst short int yy_accept[341] =
    {   0,
        0,    0,    0,    0,   77,   75,   74,   73,   45,   75,
       75,   66,   53,   51,   52,   38,   36,   64,   37,   62,
       39,   68,   63,   61,   47,   65,   47,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   56,   55,   54,   60,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   58,
       43,   59,   57,    4,    6,    5,   74,   46,    0,   70,
        0,    0,   44,    0,   40,   41,   50,    2,    1,   68,
       48,   47,   49,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   27,   67,   67,   67,   67,   24,   67,   67,

       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   27,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   42,    4,    3,    0,    0,    0,    1,   67,   67,
       67,   67,   13,   67,   67,   67,   67,   67,   67,   28,
       67,   21,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,    0,    0,   69,   10,
       67,    9,   14,   67,   67,   12,   67,   67,   25,   67,

       67,   17,   67,   67,   67,   67,   67,   67,   67,   67,
       31,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,    0,
        0,   30,   19,   67,   67,   67,   22,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   26,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
        0,    0,   67,   16,   23,   15,   67,   67,   67,   33,
       32,   18,   20,    8,   67,   67,   67,   67,    0,    0,
        0,   67,   67,   34,   67,   67,   67,   67,    0,   72,
        0,   29,   11,   67,   67,    0,    0,   72,    0,   35,

        0,    0,    0,    0,    0,    0,    0,    0,   71,    0,
       71,    0,    0,    0,    0,    0,   71,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    7,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    8,    8,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   35,   38,   39,   40,
       35,   41,   42,   43,   44,   45,   46,   35,   35,   35,
       47,   48,   49,    8,   50,    8,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   35,   60,   61,   62,   63,
       64,   65,   35,   66,   67,   68,   69,   70,   71,   35,
       35,   35,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[76] =
    {   0,
        1,    1,    2,    3,    3,    4,    5,    3,    3,    3,
        3,    3,    6,    3,    3,    3,    7,    3,    8,    8,
        3,    3,    3,    3,    9,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,    3,    3,    3,    3,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[353] =
    {   0,
        0,    0,   73,   74,  545,  967,   76,  967,  518,  532,
       25,  517,  461,  967,  967,  967,  485,  967,   65,  967,
       70,   72,  967,  967,   70,  465,   71,   78,   80,   83,
       85,   88,   91,  107,   94,  115,  117,  120,  122,  124,
      127,  967,  967,  967,  967,  129,  132,  134,  147,  150,
      154,  137,  156,  158,  152,  160,  162,  166,  168,  967,
      411,  967,  967,    0,  967,  462,  116,  967,  471,  469,
      418,  395,  967,  180,  967,  967,  967,  967,    0,  180,
      967,  967,  967,    0,  183,  186,  193,  199,  214,  218,
      225,  233,  235,  238,  242,  245,  240,  247,  252,  256,

      258,  263,  265,  270,  279,  281,  284,  287,  289,  291,
      297,  303,  305,  307,  310,  312,  315,  319,  321,  325,
      317,  323,  336,  329,  338,  331,  341,  343,  346,  353,
      355,  967,    0,  967,  396,  387,  427,    0,  358,  377,
      381,  389,  360,  396,  398,  401,  405,  403,  408,  416,
      423,  425,  427,  429,  431,  435,  437,  441,  443,  445,
      447,  452,  463,  449,  468,  472,  474,  476,  478,  482,
      484,  486,  488,  492,  494,  496,  498,  501,  503,  505,
      509,  511,  513,  515,  529,  533,  370,  365,  967,  535,
      537,  539,  541,  546,  552,  556,  560,  565,  568,  571,

      573,  576,  578,  580,  588,  590,  593,  596,  600,  603,
      606,  609,  613,  616,  621,  623,  625,  627,  629,  631,
      634,  638,  640,  636,  642,  644,  647,  649,  655,  356,
      344,  651,  657,  659,  668,  684,  670,  689,  692,  696,
      700,  702,  704,  706,  712,  717,  721,  726,  728,  732,
      734,  736,  738,  740,  742,  744,  746,  748,  750,  771,
      355,  352,  752,  754,  757,  759,  761,  782,  766,  778,
      791,  794,  796,  798,  800,  802,  804,  806,  341,  394,
      339,  808,  810,  812,  814,  816,  820,  822,  338,  362,
      363,  826,  828,  833,  830,  297,  298,  340,   83,  835,

      278,  177,  853,  261,  260,  308,  232,  253,    0,  279,
      967,  868,  228,  228,  281,  210,    0,  217,  198,  194,
      189,  174,  161,  165,  146,  140,  200,  143,  138,   97,
      107,  104,   63,  125,  119,   58,   95,   62,  967,  967,
      893,  901,  904,  914,  924,  927,  933,  939,  945,  952,
       72,  956
    } ;

static yyconst short int yy_def[353] =
    {   0,
      340,    1,  341,  341,  340,  340,  340,  340,  340,  342,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  340,  340,  340,  340,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  340,
      340,  340,  340,  344,  340,  340,  340,  340,  342,  342,
      340,  340,  340,  340,  340,  340,  340,  340,  345,  340,
      340,  340,  340,  346,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  340,  344,  340,  340,  340,  340,  345,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  340,  340,  340,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  340,
      340,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      340,  340,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  340,  340,
      340,  343,  343,  343,  343,  343,  343,  343,  340,  347,
      340,  343,  343,  343,  343,  340,  340,  347,  340,  343,

      340,  348,  349,  340,  340,  350,  348,  340,  351,  352,
      340,  349,  340,  340,  350,  340,  351,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,    0,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340
    } ;

static yyconst short int yy_nxt[1043] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,    6,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   28,   28,   34,   28,   28,   35,   28,   36,   37,
       38,   39,   28,   28,   40,   41,   42,   43,   44,   45,
       28,   46,   47,   48,   49,   50,   28,   28,   51,   28,
       52,   28,   28,   53,   54,   55,   56,   28,   57,   58,
       59,   60,   61,   62,   63,   65,   65,   67,   71,   67,
       76,  317,   78,   72,  303,   66,   66,   79,  302,   77,
       80,   80,   81,   82,   82,   83,   84,   84,   84,   84,

      302,   84,   84,   84,   84,  303,   84,   84,   88,   84,
       84,  339,   84,   84,   92,   89,   90,   67,   86,   67,
       87,   91,  338,   93,   94,   84,   84,   95,  337,   96,
      336,   97,  100,   84,   84,   84,   84,   98,   84,   84,
       84,   84,   84,   84,   99,   84,   84,   84,   84,  104,
       84,   84,   84,   84,  101,   84,   84,  102,  335,  108,
      103,  334,  107,  333,  105,   84,   84,  106,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,  111,  305,   84,   84,   84,   84,  115,  112,
      113,  332,  109,  306,  110,  114,  331,  116,   80,   80,

      122,   84,   84,  330,   84,   84,  126,  117,  329,   98,
      118,   84,   84,  119,  328,  120,  121,   84,   84,  327,
      123,  326,  140,  124,  139,  131,  125,  127,  129,  130,
      128,  137,   84,   84,  325,  137,   84,   84,  340,  142,
      141,  324,  137,   84,   84,  137,  323,  137,  306,  137,
      322,   84,   84,   84,   84,  143,   84,   84,   84,   84,
       84,   84,  144,   84,   84,   84,   84,  321,  145,  146,
       84,   84,  320,  151,   84,   84,   84,   84,  147,  148,
      149,   84,   84,   84,   84,  150,  311,  154,   84,   84,
      319,  157,  318,  153,  152,  309,  155,   84,   84,   84,

       84,  156,   84,   84,  159,   84,   84,   84,   84,   84,
       84,  316,  158,  311,  161,   84,   84,  162,  314,  160,
      163,   84,   84,   84,   84,   84,   84,  313,   84,   84,
       84,   84,  304,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,  165,  340,   84,   84,   84,
       84,   71,  164,  167,   84,   84,   84,   84,  301,   84,
       84,   84,   84,  166,   84,   84,  299,  143,  297,  168,
      170,   84,   84,   84,   84,  169,   84,   84,   84,   84,
      171,  172,  173,  174,  152,  175,  150,  177,  296,  179,
      176,  181,  178,  291,  190,   84,   84,  290,  180,   84,

       84,  183,  191,  289,  184,  281,  182,   84,   84,  280,
      192,  185,  262,  186,   84,   84,   84,   84,  261,   84,
       84,   84,   84,   84,   84,  231,   84,   84,  230,  193,
      197,  198,  199,  200,   84,   84,  189,  194,  195,  188,
      196,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,  187,  201,   84,   84,   84,   84,  136,  202,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,  203,
       84,   84,  135,  206,   70,  204,   70,  205,  209,  134,
      211,   84,   84,  132,  207,  208,   84,   84,   68,  210,
       84,   84,   84,   84,   84,   84,   84,   84,   75,  212,

       84,   84,   84,   84,   84,   84,   84,   84,   74,  190,
       84,   84,   84,   84,   84,   84,   84,   84,  213,   84,
       84,   84,   84,   84,   84,   73,  192,   84,   84,   84,
       84,   84,   84,   84,   84,  217,  216,   70,  218,  193,
      199,   68,  214,  215,  340,  196,  219,   84,   84,  340,
      202,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,  220,  340,  223,   84,   84,  340,  221,  222,  226,
       84,   84,  232,  224,   84,   84,  225,  228,   84,   84,
      227,  340,  211,   84,   84,  234,   84,   84,  233,   84,
       84,   84,   84,  229,   84,   84,   84,   84,   84,   84,

      340,  236,  235,  239,  340,  240,   84,   84,   84,   84,
      238,   84,   84,  237,   84,   84,  340,  241,   84,   84,
      340,   84,   84,  242,   84,   84,  340,   84,   84,  244,
      246,   84,   84,  243,   84,   84,  340,  245,  247,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,  340,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,  340,   84,   84,   84,   84,   84,
       84,  340,  232,   84,   84,   84,   84,   84,   84,  248,
      340,  252,  340,  233,  253,  250,   84,   84,   84,   84,
      249,  251,  254,  340,  237,  340,  263,  264,  255,  259,

      257,  256,   84,   84,  340,  260,  258,   84,   84,  247,
       84,   84,  340,  265,   84,   84,  340,  266,   84,   84,
       84,   84,   84,   84,   84,   84,  340,  269,  340,  270,
       84,   84,  340,  272,  267,   84,   84,  340,  268,   84,
       84,  271,  340,  273,   84,   84,   84,   84,  340,  274,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,  279,   84,   84,   84,   84,   84,
       84,  340,  264,  340,   84,   84,  265,  266,  275,   84,
       84,  340,  278,  340,  270,  282,   84,   84,  272,  283,

       84,   84,  340,  276,  273,  277,  271,  274,  285,   84,
       84,  284,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,  340,  292,   84,   84,
       84,   84,  340,  294,   84,   84,   84,   84,   84,   84,
      293,   84,   84,   84,   84,  340,  340,  340,  284,  308,
      340,  300,  340,  340,  340,  287,  340,  340,  286,  309,
      292,  310,  310,  288,  340,  340,  295,  311,  340,  340,
      340,  340,  340,  300,  309,  293,  310,  310,  340,  340,
      340,  340,  311,   64,   64,   64,   64,   64,   64,   64,

       64,   64,   64,   69,   69,   69,   69,   69,   69,   69,
       69,   85,  340,   85,  133,  340,  133,  133,  133,  340,
      133,  133,  133,  133,  138,  340,  138,  138,  138,  138,
      138,  138,  138,  138,   84,  340,   84,  298,  340,  340,
      298,  340,  298,  307,  340,  307,  307,  340,  307,  312,
      340,  312,  312,  312,  312,  315,  340,  340,  340,  340,
      340,  315,  310,  310,  340,  310,    5,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,

      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340
    } ;

static yyconst short int yy_chk[1043] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    7,   11,    7,
       19,  351,   21,   11,  338,    3,    4,   21,  299,   19,
       22,   22,   25,   25,   27,   27,   28,   28,   29,   29,

      337,   30,   30,   31,   31,  299,   32,   32,   30,   33,
       33,  336,   35,   35,   31,   30,   30,   67,   29,   67,
       29,   30,  335,   31,   32,   34,   34,   33,  334,   33,
      333,   33,   35,   36,   36,   37,   37,   34,   38,   38,
       39,   39,   40,   40,   34,   41,   41,   46,   46,   38,
       47,   47,   48,   48,   36,   52,   52,   37,  332,   41,
       37,  331,   40,  330,   39,   49,   49,   39,   50,   50,
       55,   55,   51,   51,   53,   53,   54,   54,   56,   56,
       57,   57,   47,  302,   58,   58,   59,   59,   48,   47,
       47,  329,   46,  302,   46,   47,  328,   48,   80,   80,

       52,   85,   85,  327,   86,   86,   55,   49,  326,   51,
       50,   87,   87,   50,  325,   50,   51,   88,   88,  324,
       53,  323,   87,   54,   86,   59,   54,   56,   57,   58,
       56,   74,   89,   89,  322,   74,   90,   90,  307,   89,
       88,  321,   74,   91,   91,   74,  320,   74,  307,   74,
      319,   92,   92,   93,   93,   90,   94,   94,   97,   97,
       95,   95,   91,   96,   96,   98,   98,  318,   91,   92,
       99,   99,  316,   97,  100,  100,  101,  101,   93,   94,
       95,  102,  102,  103,  103,   96,  315,  101,  104,  104,
      314,  103,  313,  100,   99,  310,  102,  105,  105,  106,

      106,  102,  107,  107,  105,  108,  108,  109,  109,  110,
      110,  308,  104,  306,  106,  111,  111,  107,  305,  105,
      108,  112,  112,  113,  113,  114,  114,  304,  115,  115,
      116,  116,  301,  117,  117,  121,  121,  118,  118,  119,
      119,  122,  122,  120,  120,  110,  298,  124,  124,  126,
      126,  297,  109,  112,  123,  123,  125,  125,  296,  127,
      127,  128,  128,  111,  129,  129,  291,  113,  290,  114,
      115,  130,  130,  131,  131,  114,  139,  139,  143,  143,
      116,  117,  118,  120,  121,  122,  119,  124,  289,  125,
      123,  127,  124,  281,  139,  140,  140,  280,  126,  141,

      141,  128,  140,  279,  129,  262,  127,  142,  142,  261,
      141,  130,  231,  131,  144,  144,  145,  145,  230,  146,
      146,  148,  148,  147,  147,  188,  149,  149,  187,  142,
      146,  147,  148,  149,  150,  150,  137,  144,  144,  136,
      145,  151,  151,  152,  152,  153,  153,  154,  154,  155,
      155,  135,  151,  156,  156,  157,  157,   72,  153,  158,
      158,  159,  159,  160,  160,  161,  161,  164,  164,  154,
      162,  162,   71,  157,   70,  155,   69,  156,  160,   66,
      162,  163,  163,   61,  158,  159,  165,  165,   26,  161,
      166,  166,  167,  167,  168,  168,  169,  169,   17,  163,

      170,  170,  171,  171,  172,  172,  173,  173,   13,  164,
      174,  174,  175,  175,  176,  176,  177,  177,  165,  178,
      178,  179,  179,  180,  180,   12,  166,  181,  181,  182,
      182,  183,  183,  184,  184,  171,  170,   10,  173,  167,
      172,    9,  168,  168,    5,  169,  174,  185,  185,    0,
      175,  186,  186,  190,  190,  191,  191,  192,  192,  193,
      193,  176,    0,  179,  194,  194,    0,  177,  178,  182,
      195,  195,  191,  180,  196,  196,  181,  184,  197,  197,
      183,    0,  185,  198,  198,  195,  199,  199,  194,  200,
      200,  201,  201,  186,  202,  202,  203,  203,  204,  204,

        0,  198,  197,  203,    0,  204,  205,  205,  206,  206,
      201,  207,  207,  200,  208,  208,    0,  205,  209,  209,
        0,  210,  210,  206,  211,  211,    0,  212,  212,  208,
      210,  213,  213,  207,  214,  214,    0,  209,  212,  215,
      215,  216,  216,  217,  217,  218,  218,  219,  219,  220,
      220,    0,  221,  221,  224,  224,  222,  222,  223,  223,
      225,  225,  226,  226,    0,  227,  227,  228,  228,  232,
      232,    0,  213,  229,  229,  233,  233,  234,  234,  215,
        0,  220,    0,  214,  221,  217,  235,  235,  237,  237,
      216,  219,  222,    0,  218,    0,  234,  235,  223,  227,

      225,  224,  236,  236,    0,  228,  226,  238,  238,  229,
      239,  239,    0,  236,  240,  240,    0,  238,  241,  241,
      242,  242,  243,  243,  244,  244,    0,  241,    0,  242,
      245,  245,    0,  244,  239,  246,  246,    0,  240,  247,
      247,  243,    0,  245,  248,  248,  249,  249,    0,  246,
      250,  250,  251,  251,  252,  252,  253,  253,  254,  254,
      255,  255,  256,  256,  257,  257,  258,  258,  259,  259,
      263,  263,  264,  264,  260,  265,  265,  266,  266,  267,
      267,    0,  249,    0,  269,  269,  250,  251,  248,  260,
      260,    0,  254,    0,  255,  263,  270,  270,  257,  267,

      268,  268,    0,  252,  258,  253,  256,  259,  269,  271,
      271,  268,  272,  272,  273,  273,  274,  274,  275,  275,
      276,  276,  277,  277,  278,  278,  282,  282,  283,  283,
      284,  284,  285,  285,  286,  286,    0,  282,  287,  287,
      288,  288,    0,  285,  292,  292,  293,  293,  295,  295,
      283,  294,  294,  300,  300,    0,    0,    0,  277,  303,
        0,  294,    0,    0,    0,  276,    0,    0,  275,  303,
      286,  303,  303,  278,  312,    0,  288,  303,    0,    0,
        0,    0,    0,  295,  312,  287,  312,  312,    0,    0,
        0,    0,  312,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  342,  342,  342,  342,  342,  342,  342,
      342,  343,    0,  343,  344,    0,  344,  344,  344,    0,
      344,  344,  344,  344,  345,    0,  345,  345,  345,  345,
      345,  345,  345,  345,  346,    0,  346,  347,    0,    0,
      347,    0,  347,  348,    0,  348,  348,    0,  348,  349,
        0,  349,  349,  349,  349,  350,    0,    0,    0,    0,
        0,  350,  352,  352,    0,  352,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,

      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\CS224_P1_2021438_2021193_2021051.l"
#define INITIAL 0
#line 3 ".\\CS224_P1_2021438_2021193_2021051.l"
	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	int lineno = 1;
	void printToken(char *TOKEN);
	FILE * oFile; 
	FILE *iFile;
    void printOut(FILE *oFile);
	void yyerror();
#define ML_COMMENT 1

#line 725 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 29 ".\\CS224_P1_2021438_2021193_2021051.l"


#line 879 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 341 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 967 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printf("comment out single line %d\n", lineno); } 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printf("Comment out starting line %d ", lineno); BEGIN(ML_COMMENT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 34 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printf("to line %d\n", lineno); BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 ".\\CS224_P1_2021438_2021193_2021051.l"

	YY_BREAK
case 5:
YY_RULE_SETUP
#line 36 ".\\CS224_P1_2021438_2021193_2021051.l"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 37 ".\\CS224_P1_2021438_2021193_2021051.l"
{ lineno += 1; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 39 ".\\CS224_P1_2021438_2021193_2021051.l"
{printToken("using_namespace_std");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 40 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_SWITCH"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 41 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_CASE"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_BOOL"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_OPERATOR"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_COUT"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_CIN"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_CHAR"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 47 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_FRIEND"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_DELETE"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 49 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_LONG"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 50 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_STATIC"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 51 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_CONST"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 52 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_STRING"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 53 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_INT"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 54 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_FLOAT"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 55 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_DOUBLE"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 56 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_IF"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 57 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_ELSE"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 58 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_WHILE"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 59 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_DO"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 60 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_FOR"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 61 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_CONTINUE"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 62 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_BREAK"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 63 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_VOID"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 64 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_RETURN"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 65 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_PUBLIC"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 66 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_PRIVATE"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 67 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("KW_PROTECTED"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("ADDOP"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("SUBOP"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("MULOP"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 73 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("DIVOP"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 74 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("INCR"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 75 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("INCR"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 76 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("OROR"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 77 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("OR"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 78 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("ANDOP"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("NOTOP"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("EQUOP"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 81 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("RELOP"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 82 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("INSERTIONOP"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 83 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("EXTRACTIONOP"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 84 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("ARROW"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 87 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("LPAREN"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 88 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("RPAREN"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 89 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("SINGLEQUOTATION"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 90 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("LBRACK"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 91 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("BACKSLASH"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 92 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("RBRACK"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 93 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("TILDE"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 94 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("LBRACE"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 95 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("RBRACE"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 96 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("UNDERSCORE"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 97 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("SEMI"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 98 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("DOT"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 99 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("COLON"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 100 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("COMMA"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 101 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("ASSIGN"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 102 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("REFER"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 105 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("VARIABLE"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 106 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("INT_CONST"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 107 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("END_LINE"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 108 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("STRING"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 109 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("PREPROCESSOR");}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 110 ".\\CS224_P1_2021438_2021193_2021051.l"
{ printToken("DEFINE");}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 113 ".\\CS224_P1_2021438_2021193_2021051.l"
{ lineno += 1; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 114 ".\\CS224_P1_2021438_2021193_2021051.l"

	YY_BREAK
case 75:
YY_RULE_SETUP
#line 116 ".\\CS224_P1_2021438_2021193_2021051.l"
{ yyerror("Unrecognized character"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 118 ".\\CS224_P1_2021438_2021193_2021051.l"
ECHO;
	YY_BREAK
#line 1342 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ML_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 341 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 341 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 340);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 118 ".\\CS224_P1_2021438_2021193_2021051.l"


void printToken(char *TOKEN){
	printf("Token: %s\ttoken_id: %s\tlineno: %d\n", yytext, TOKEN, lineno);
    fprintf(oFile,"%s, %s, %d\n", yytext, TOKEN, lineno);
    // fprintf(oFile,"Token: %s\ttoken_id: %s\tlineno: %d\n", yytext, TOKEN, lineno);
}

void yyerror(char *message){
	printf("Error: \"%s\" in line %d. Token = %s\n", message, lineno, yytext);
	exit(1);
}

int main(int argc, char *argv[]){

	yyin = fopen("case4.cpp","r");
	
	if(yyin==NULL)
	{
		printf("ERROR Input source not found\n");
		exit(1);
	}
	oFile=fopen("output.csv", "w");
	yylex();
	fclose(yyin);
	return 0;
}